export const ERRORS = {
  NO_CREDENTIALS       : "NO_CREDENTIALS",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  INVALID_OTP_CODE     : "INVALID_OTP_CODE",
  OTP_CODE_EXPIRE_IN   : "OTP_CODE_EXPIRE_IN",
  INVALID_OLD_PASSWORD : "INVALID_OLD_PASSWORD",
  INVALID_OTP_METHOD   : "INVALID_OTP_METHOD",
  INVALID_SESSION_SCOPE: "INVALID_SESSION_SCOPE",
  INVALID_OTP_CHARSET  : "INVALID_OTP_CHARSET",
  USER_NOTFOUND        : "USER_NOTFOUND",
  BAD_REQUEST          : "BAD_REQUEST",
  EMAIL_ALREADY_EXISTS : "EMAIL_ALREADY_EXISTS"
};